server:
  servlet:
    port: 9080
    contextPath: /api

spring:

  application:
    name:

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/quora
    username: postgres
#<<<<<<< Updated upstream
#    password: divyankadmin
#=======
    password: postgres
#>>>>>>> Stashed changes

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect